Added new models
NXTGENDASHBOARD/cerberus-api pull request #1
Opened 2021-12-21 16:24 UTC by AdaptIT-andrew

I added the fields to Applications and added a Courses.

2021-12-22 06:49 UTC, FreedomK247 commented on Cerberus.Dashboard.Api/appsettings.Development.json
> -    "DefaultConnection": "Host=localhost;Port=5432;Database=dev-cerberusAnalyticsDb;Username=postgres;Password=Welcome@1;"
For now we'll add this to gitignore - we have different passwords

2021-12-22 06:53 UTC, FreedomK247 requested changes
Please see comments regarding Address fields on the Application.

2021-12-22 06:53 UTC, FreedomK247 commented on Cerberus.Dashboard.Domain/Models/Application.cs
> +        public string PostalAddressCity { get; set; }
Since we are repeating these fields why Dont we have an Address Entity separated by AddressType(Physical or Postal and  Work)

2021-12-22 08:59 UTC, AdaptIT-andrew commented
@FreedomK247 I have made changes to the Application model added the Address model.

2021-12-23 06:19 UTC, FreedomK247 approved these changes

2021-12-23 06:19 UTC, merged